### ISSUE TITLE
StandartIcerikDenetim adında bir tablo yapılacak.

### ISSUE THREAD

**Issue by ghost** [halilpoyraz/Tse#3]
Tablonun adı belki değişebilir ama alanlarının aşağıdaki gibi olması öngörülmektedir.

StandartIcerikDenetimID	int	Unchecked
StandartID	int	Unchecked
StandartIcerikID	int	Unchecked
Secmeli	bit	Unchecked
Zorunlu	bit	Unchecked
BilgiAmacli	bit	Unchecked
KYS	bit	Unchecked
US	bit	Unchecked
DurumID	int	Unchecked

**Comment by halilpoyraz** [comment]
Tablo oluşturuldu. 
Bağlantıları oluşturuldu. 
DummyData girildi.
